CREATE TABLE certificate (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, `from` DATETIME DEFAULT NULL, `to` DATETIME DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE certificate ADD user_id INT DEFAULT NULL;
ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
CREATE INDEX IDX_219CDA4AA76ED395 ON certificate (user_id);
